export const VIDEOCONSULTA_ESTADOS = {
  PENDIENTE:  'PENDIENTE',
  EN_CURSO:   'EN_CURSO',
  COMPLETADA: 'COMPLETADA',
  CANCELADA:  'CANCELADA',
} as const;

export const SESION_ESTADOS = {
  ACTIVA:       'ACTIVA',
  FINALIZADA:   'FINALIZADA',
  INTERRUMPIDA: 'INTERRUMPIDA',
} as const;

export const PARTICIPANTE_ROLES = {
  DOCTOR:   'DOCTOR',
  PACIENTE: 'PACIENTE',
  INVITADO: 'INVITADO',
} as const;